import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../../components/Navbar/page";

export const metadata: Metadata = {
  title: "Agrandi Technologies Inc.",
  description: "Generated by Agrandi Technologies",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <NavBar />
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
